### ISSUE TITLE
why I cant break the bedrock

### ISSUE THREAD

**Issue by zdwnss** [rockerle/BedrockMiner#1]
I pressed 'b'
![image](https://user-images.githubusercontent.com/110908573/183821721-50d94c4d-47e0-44ed-9dd4-66cbe1323b81.png)
![image](https://user-images.githubusercontent.com/110908573/183822226-5b59c41b-2f1f-4bd1-b5e9-d98b4ea52c05.png)

**Comment by rockerle** [comment]
Which version, server brand and do you have very high ping? For paper/spigot/... server configs headless pistons must be allowed.

**Comment by zdwnss** [comment]
no this is a Vanilla server

**Comment by rockerle** [comment]
I tried it in 1.19.2 Singleplayer and Multiplayer Vanilla and both worked fine for me. If you want more help with your issue please record a short clip where it is not working.

Singleplayer: https://imgur.com/a/ILeBahR
Multiplayer: https://imgur.com/a/2N9a369

**Comment by zdwnss** [comment]
this server became a fabric server=(
Can I use this mod?

**Comment by rockerle** [comment]
you can use this mod on any server that has a configuration to allow pistons without a head (called headless pistons). That's the mechanic this mod works with. In paper/spigot server there is a property named smth like **"enable-headless-pistons"** that must be set to true. 
What also can happen is, that any kind of anti cheat is not happy with the way this mod is placing pistons without having a direct line of sight with the block position.
