### ISSUE TITLE
Can't break despite meeting requirements

### ISSUE THREAD

**Issue by somebirby** [rockerle/BedrockMiner#3]
Mod refuses to function despite meeting the requirements:

![image](https://user-images.githubusercontent.com/16958149/221355164-8c14879b-415e-4db1-86b3-e93f97cc1ab4.png)
![image](https://user-images.githubusercontent.com/16958149/221355237-b078b017-07b9-4bab-ad76-1da4c163aeff.png)

I do not have any other mod installed

**Comment by rockerle** [comment]
Is it not working in Singleplayer/Multiplayer? Are you playing on a vanilla Minecraft version or on a bukket/Spigot/Paper/... Server and do you have a high ping if so? And what mc verion are you using?

**Comment by somebirby** [comment]
Multiplayer Fabric server, with only very few optimization mods, to my knowledge, but it already worked without any issues a few weeks ago.
Stable ~80 ping
1.19.3

**Comment by rockerle** [comment]
What I forgot to ask is that it doesn't work in general, right? 
Do you by any chance switched between servers/worlds in a single game session?
I experienced some quirky built setups with the mod myself, but you are not talking about a single location that is problematic? I will look into it.

**Comment by somebirby** [comment]
Same server, didn't load a singleplayer world, tried relaunching Minecraft. Nothing.

**Comment by rockerle** [comment]
Hi again,
sadly the only way i could reproduce your specific issue was by dropping all pistons in a world and switching to a different world/server in the same play session.
I made a tweaked version [here](https://github.com/rockerle/BedrockMiner/releases/tag/test) I would ask you to test.
I hope the changes helped your case or gives via the extensive chat messaging more details about your issue and I can provide a new proper working release after the weekend.

Edit: If Bedrock is too risky/expensive for you to try it out you can right click any block with an item to add/remove it to the list of "piston mineable" blocks

**Comment by somebirby** [comment]
It works now! It can mine bedrock no problem now!
Thank you for your time and effort 🙇🏻

**Comment by somebirby** [comment]
Woops, only did a single test and spoke too soon apparently.
As soon as I went back in and tried to dig another block, it says it can't find a suitable location anymore, anywhere on the Nether roof:
![image](https://user-images.githubusercontent.com/16958149/222500520-6ef18ba3-c6ba-49ad-b4fb-8d9c910896f1.png)

EDIT:
It now only allows breaking blocks a little while after connecting, or after switching the mod off & on again.
So as far as I'm concerned, it works ahah

**Comment by rockerle** [comment]
I'm glad to hear it kinda resolved itself (to a certain degree).

Im anyways cleaning up the test build and make a new release ready to solve other issues.
Most important feature will be a proper hard reset when re-toggeling the miner, so most issues (hopefully) can be resolved just by trying again.
