### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by xiaoao1314** [rockerle/BedrockMiner#4]
I downloaded version 1.20.2 but reported an error after starting the client
![3U9~L{XMV7@AG@~HS(Y C91](https://github.com/rockerle/BedrockMiner/assets/149850592/cdba791d-b4c4-4583-b88c-58949ce4080d)

**Comment by rockerle** [comment]
Thank you for letting me know. A new version was uploaded to the release page that works in 1.20.2 :)
